main:
  push:
    "volume-cache":
      name: äº‘åŽŸç”Ÿæž„å»º
      runner:
        cpus: 64
      imports:	
        - https://cnb.cool/onedayxyy/secret/-/blob/main/envs.yml
      docker:
        image: node:22
      stages:
        - name: set env
          script: echo -n $(date +%s)
          exports:
            info: CUSTOM_ENV_START_TIME
        - name: ðŸ ï¸ è®¾ç½®æ·˜å®æº
          script: |
            npm config set registry https://registry.npmmirror.com
        - name: ðŸ–¨ï¸ æ‰“å°çŽ¯å¢ƒ
          script: |
            npm install -g pnpm && node -v && npm -v && yarn -v && pnpm -v
        - name: ðŸ“¦ï¸ å®‰è£…ä¾èµ–
          script: |
            pnpm install
        - name: âš—ï¸ ç¼–è¯‘é¡¹ç›®
          script: |
            pnpm docs:build
        - name: ðŸšš éƒ¨ç½²åˆ°Pages
          image: node:22
          script: >-
            npx edgeone pages deploy ./docs/.vitepress/dist --name
            vitepress-theme-teek-one-public --token $EDGEONE_PAGES_API_TOKEN


        # #åŒæ­¥ä»“åº“åˆ°gitee                  
        # - name: sync to gitee
        #   image: tencentcom/git-sync
        #   settings:
        #     branch: master
        #     auth_type: https
        #     username: ${GIT_USERNAME}
        #     password: ${GIT_ACCESS_TOKEN}
        #     target_url: https://gitee.com/onlyonexl/vitepress-theme-teek-one-private.git
        #     # git_email: 'github-actions[bot]@users.noreply.github.com'

        - name: build knowledge base
          image: cnbcool/knowledge-base
          settings:
            embedding_model: bge-m3
            include: "**/**.md"
            exclude: ""    

        - name: â±ï¸ è®¡ç®—è€—æ—¶
          script: |
            # è®¡ç®—è€—æ—¶
            end_time=$(date +%s)
            duration=$((end_time - $CUSTOM_ENV_START_TIME))
            minutes=$((duration / 60))
            seconds=$((duration % 60))
            time_str="${minutes}åˆ†${seconds}ç§’"
            echo -n ${time_str}
          exports:
            info: CUSTOM_ENV_BUILD_TIME

            
        # - name: é’‰é’‰é€šçŸ¥
        #   image: tencentcom/dingtalk-bot-msg:latest
        #   settings:
        #     content: "ã€ŒTeek-one Blogã€å‘å¸ƒå®Œæˆï¼Œè€—æ—¶: ${CUSTOM_ENV_BUILD_TIME}"
        #     c_type: "text" # æ”¯æŒ: text, markdown, link, actionCard, multiActionCard, feedCard
        #     secret: $SECRET
        #     webhook: $WEBHOOK
        #     isAtAll: false
        #     debug: false # æ–°å¢ž: æ˜¯å¦å¯ç”¨è°ƒè¯•æ¨¡å¼

        # - name: ðŸ”” å‘å¸ƒé€šçŸ¥  
        #   image: tencentcom/wecom-message
        #   settings:
        #     robot: ${WECOM_BOT}
        #     msgType: markdown
        #     content: |
        #       > **ðŸŽ‰ One Blog åˆä¸€æ¬¡å‘å¸ƒæˆåŠŸå•¦ï¼**   
        #       > **æž„å»ºæ—¶é—´:** $CUSTOM_ENV_DATE_INFO 
        #       > **æž„å»ºè€—æ—¶:** ${CUSTOM_ENV_BUILD_TIME}        
        #       > **æž„å»ºid:** $CNB_BUILD_ID  
        #       > **æäº¤id:** $CNB_COMMIT_SHORT            
        #       > **æž„å»ºåˆ†æ”¯:** $CNB_BRANCH
        #       > **æäº¤ä¿¡æ¯:** $CNB_COMMIT_MESSAGE_TITLE
        #       > **æäº¤è€…:** $CNB_COMMITTER
        #       > **ä»“åº“åœ°å€:** [$CNB_REPO_URL_HTTPS]($CNB_REPO_URL_HTTPS)
        #       > **æˆ‘çš„ç½‘ç«™:** [onedayxyy.cn](https://onedayxyy.cn/)            