import {
  VscodeDark,
  WebstormDark,
  Postman,
  Html,
  Css,
  Javascript,
  Typescript,
  Sass,
  LessDark,
  TailwindcssDark,
  VuejsDark,
  ViteDark,
  PiniaDark,
  Electron,
  LinuxDark,
  Nginx,
  NodejsDark,
  MysqlDark,
  PnpmDark,
  ReactDark,
  Git,
  GithubDark,
  GitlabDark,
  Docker,
  JAVA,
  IDEA,
  DataGrip,
  RedisDark,
  RabbitMqDark,
  SpringDark,
  SpringBootDark,
  NpmDark,
  Android,
  MavenDark,
  Star,
  Fork,
  View,
} from "./TechIcons";

export const profile = {
  title: '你好，我是',
  name: 'sakaay|飒龘',
  desc: '当以读书通世事',
  avatar: '/img/xyy.webp',//头像
  buttons: [
    { text: '联系我', link: 'mailto:3206908770@qq.com', type: 'primary' },
    { text: '查看项目', link: '/teek', type: 'default' }
  ],
};

export const majorSkills = [
  {
    name: "后端与数据库",
    percent: 75,
    color: "#f25e62",
    tags: [
      { name: "Java", bg: "#ffeaea", color: "#f25e62" },
      { name: "Spring", bg: "#f3eaff", color: "#88619a" },
      { name: "Maven", bg: "#eaf6ff", color: "#4298b4" },
      { name: "MySQL", bg: "#eafff3", color: "#33a474" },
      { name: "MongoDB", bg: "#eafff3", color: "#33a474" },
      { name: "Oracle", bg: "#fff7ea", color: "#e4ae3a" },
      { name: "Node.js", bg: "#f3ffe9", color: "#96b466" },
    ],
  },
  {
    name: "前端开发",
    percent: 88,
    color: "#33a474",
    tags: [
      { name: "HTML5", bg: "#eaf6ff", color: "#4298b4" },
      { name: "CSS3", bg: "#e3edfa", color: "#3976c6" },
      { name: "Sass", bg: "#ffeaf6", color: "#d72660" },
      { name: "Less", bg: "#f3eaff", color: "#88619a" },
      { name: "JavaScript", bg: "#fffbe6", color: "#e4ae3a" },
      { name: "TypeScript", bg: "#e3edfa", color: "#3976c6" },
    ],
  },
  {
    name: "前端框架",
    percent: 85,
    color: "#4298b4",
    tags: [
      { name: "Vue", bg: "#eaf6ff", color: "#4298b4" },
      { name: "React", bg: "#e3edfa", color: "#3976c6" },
      { name: "Angular", bg: "#ffeaea", color: "#f25e62" },
      { name: "Next.js", bg: "#f3ffe9", color: "#96b466" },
    ],
  },
  {
    name: "工程化与工具",
    percent: 83,
    color: "#e4ae3a",
    tags: [
      { name: "Vite", bg: "#fffbe6", color: "#e4ae3a" },
      { name: "Webpack", bg: "#e3edfa", color: "#3976c6" },
      { name: "Git", bg: "#f3eaff", color: "#88619a" },
      { name: "Docker", bg: "#eafff3", color: "#33a474" },
    ],
  },
  {
    name: "运维与Linux",
    percent: 86,
    color: "#96b466",
    tags: [
      { name: "Nginx", bg: "#e3edfa", color: "#3976c6" },
      { name: "HAProxy", bg: "#ffeaea", color: "#f25e62" },
      { name: "Kubernetes", bg: "#eafff3", color: "#33a474" },
      { name: "Wireshark", bg: "#f3eaff", color: "#88619a" },
      { name: "Fail2Ban", bg: "#fffbe6", color: "#e4ae3a" },
    ],
  },
];

export const techStackIcons = [
  // 第一行，首尾空
  {},
  { name: "JAVA", icon: JAVA },
  { name: "IDEA", icon: IDEA },
  { name: "Webstorm", icon: WebstormDark },
  { name: "DataGrip", icon: DataGrip },
  { name: "Spring", icon: SpringDark },
  { name: "SpringBoot", icon: SpringBootDark },
  {},
  // 第二行
  { name: "Mysql", icon: MysqlDark },
  { name: "Redis", icon: RedisDark },
  { name: "RabbitMq", icon: RabbitMqDark },
  { name: "Html", icon: Html },
  { name: "Css", icon: Css },
  { name: "Javascript", icon: Javascript },
  { name: "Typescript", icon: Typescript },
  { name: "VscodeDark", icon: VscodeDark },
  // 第三行
  { name: "Vuejs", icon: VuejsDark },
  { name: "Vite", icon: ViteDark },
  { name: "Pinia", icon: PiniaDark },
  { name: "Linux", icon: LinuxDark },
  { name: "Nginx", icon: Nginx },
  { name: "Nodejs", icon: NodejsDark },
  { name: "ReactDark", icon: ReactDark },
  { name: "Tailwindcss", icon: TailwindcssDark },
  // 第四行，首尾空
  {},
  { name: "Npm", icon: NpmDark },
  { name: "Git", icon: Git },
  { name: "Github", icon: GithubDark },
  { name: "Postman", icon: Postman },
  { name: "Docker", icon: Docker },
  { name: "Maven", icon: MavenDark },
  {},
  // 第五行，缩小行
  {},
  { name: "Android", icon: Android, small: true },
  { name: "Pnpm", icon: PnpmDark, small: true },
  { name: "Electron", icon: Electron, small: true },
  { name: "Sass", icon: Sass, small: true },
  { name: "LessDark", icon: LessDark, small: true },
  { name: "GitlabDark", icon: GitlabDark, small: true },
  {},
];

export const ossProjects = [
  {
    name: "题王 QKing 局域网答题系统",
    desc: "🏫 局域网课堂实时答题与整卷测验，支持 Excel 操作题、编程题自动判分，单文件免安装运行。",
    tag: { name: "Python", bg: "#e3edfa", color: "#3976c6" },
    projectsimg: "https://img.sakaay.com/d/img/bz/20251214_183312_6280.avif",
    visit: "dd.sakaay.com",
    url: "https://dd.sakaay.com",
    github: "https://github.com/sa-da-sa-da",
    btnText: "访问站点",
  },
  {
    name: "青少年编程教学模拟训练软件",
    desc: "💻 面向青少年的 Python 编程教学与模拟训练站，含趣味教程、闯关练习与 AI 编程助手。",
    tag: { name: "JavaScript", bg: "#fffbe6", color: "#e4ae3a" },
    projectsimg: "https://img.sakaay.com/d/img/bz/20251214_183312_6280.avif",
    visit: "e.sakaay.com",
    url: "https://e.sakaay.com",
    github: "https://github.com/sa-da-sa-da",
    btnText: "访问站点",
  },
  {
    name: "AI 生图与图像编辑",
    desc: "🎨 基于千问 IMAGE 模型的 AI 生图与图像编辑应用，一键生成教学配图与素材。",
    tag: { name: "AI", bg: "#f3eaff", color: "#88619a" },
    projectsimg: "https://img.sakaay.com/d/img/bz/20251214_183312_6280.avif",
    visit: "aitu.sakaay.com",
    url: "https://aitu.sakaay.com",
    github: "https://github.com/sa-da-sa-da",
    btnText: "访问站点",
  },
  {
    name: "高中信息技术 · 知识库",
    desc: "📚 「高中信息技术」共建知识库，汇集教学经验、题库与踩坑记录，邀请你一起问答。",
    tag: { name: "知识库", bg: "#eafff3", color: "#33a474" },
    projectsimg: "https://img.sakaay.com/d/img/bz/20251214_183312_6280.avif",
    visit: "金山文档",
    url: "https://www.kdocs.cn/wiki/share/3199933675?invite_key=g18i5ds",
    github: "https://www.kdocs.cn/wiki/share/3199933675?invite_key=g18i5ds",
    btnText: "加入问答",
  },
  {
    name: "青少年编程训练软件",
    desc: "🎉 一款面向中小学学生的编程训练软件，帮助学生提升编程能力和兴趣。",
    tag: { name: "python", bg: "#e3edfa", color: "#3976c6" },
    projectsimg: "https://img.sakaay.com/d/img/bz/20251214_183312_6280.avif",
    Star: '35.0k',
    Fork: '12.6k',
    View: '32.6k',
    github: "https://onedayxyy.cn/teek",
  },
  {
    name: "Typora-One",
    desc: "Teek 是一个轻量、简洁高效、灵活配置、易于扩展的 VitePress 主题 ✨",
    tag: { name: "JavaScript", bg: "#fffbe6", color: "#e4ae3a" },
    projectsimg: "https://img.sakaay.com/d/img/bz/20251214_183312_6280.avif",
    Star: '96.8k',
    Fork: '46.2k',
    View: '79.3k',
    github: "https://onedayxyy.cn/typora-theme-one",
  },
];

// 导出开源项目图标用于子组件
export { Star, Fork, View };
